/* ========================================================= //<>//
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:Goedning:820935:
  
  println("Goedning - GDropList >> GEvent." + event + " @ " + millis()); //<>//
  
  
} //_CODE_:Goedning:820935:

public void dropList1_click2(GDropList source, GEvent event) { //_CODE_:Jordtype:594344:
  println("Jordtype - GDropList >> GEvent." + event + " @ " + millis());
  
} //_CODE_:Jordtype:594344:

public void dropList1_click3(GDropList source, GEvent event) { //_CODE_:Afgroed:675680:
  println("Afgroed - GDropList >> GEvent." + event + " @ " + millis());
  
} //_CODE_:Afgroed:675680:

public void button1_click1(GButton source, GEvent event) { //_CODE_:Beregn:373559:
  println("Beregn - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Beregn:373559:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){ //<>//
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  
  //******** laver gødning liste
  Goedning = new GDropList(this, 5, 5, 90, 60, 2, 10);
  //Goedning.setItems(loadStrings("list_820935"), 0);
  Goedning.setItems(getGodning(), 0);
  Goedning.addEventHandler(this, "dropList1_click1");
  
  
  Jordtype = new GDropList(this, 103, 5, 90, 180, 8, 10);
  //Jordtype.setItems(loadStrings("list_594344"), 0);
  Jordtype.setItems(getJordTyper(), 0);
  
  Jordtype.addEventHandler(this, "dropList1_click2");
  Afgroed = new GDropList(this, 203, 5, 90, 140, 6, 10);
  Afgroed.setItems(loadStrings("list_675680"), 0);
  Afgroed.addEventHandler(this, "dropList1_click3");
  Beregn = new GButton(this, 6, 100, 80, 30);
  Beregn.setText("Beregn");
  Beregn.addEventHandler(this, "button1_click1");
}

// Variable declarations 
// autogenerated do not edit
GDropList Goedning; 
GDropList Jordtype; 
GDropList Afgroed; 
GButton Beregn; 
