/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void textfield2_change1(GTextField source, GEvent event) { //_CODE_:antalN:835496:
  println("textfield2 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:antalN:835496:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:429774:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:429774:

public void custom_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:custom_slider1:519292:
  println("custom_slider1 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:custom_slider1:519292:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  text1 = new GLabel(this, 5, 5, 113, 22);
  text1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  text1.setText("% N i gødningen");
  text1.setOpaque(false);
  label1 = new GLabel(this, 5, 66, 160, 28);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Ønsket mængde af N pr. ha");
  label1.setOpaque(false);
  antalN = new GTextField(this, 186, 71, 89, 22, G4P.SCROLLBARS_NONE);
  antalN.setOpaque(true);
  antalN.addEventHandler(this, "textfield2_change1");
  button1 = new GButton(this, 165, 240, 80, 30);
  button1.setText("Beregn");
  button1.addEventHandler(this, "button1_click1");
  custom_slider1 = new GCustomSlider(this, 182, 2, 100, 40, "grey_blue");
  custom_slider1.setLimits(0.5, 0.0, 1.0);
  custom_slider1.setNumberFormat(G4P.DECIMAL, 2);
  custom_slider1.setOpaque(false);
  custom_slider1.addEventHandler(this, "custom_slider1_change1");
}

// Variable declarations 
// autogenerated do not edit
GLabel text1; 
GLabel label1; 
GTextField antalN; 
GButton button1; 
GCustomSlider custom_slider1; 
